### ISSUE TITLE
2 computers connecting to the same redpitaya can corrupt the system

### ISSUE THREAD

**Issue by SamuelDeleglise** [lneuhaus/pyrpl#315] opened 2017-08-18 10:53 UTC
Then, the only way is to reboot the redpitaya. This can be quite annoying (by the way, this could be the reason why arroseur goes down from time to time).

I wonder if it could be avoided by preventing a kicked out process from reconnecting ever again...

**Comment by lneuhaus** [comment] 2017-08-18 15:06
duplicate of #274 
Let's continue the discussion there..

**Closed** 2017-08-18 15:06 UTC
Labels: duplicate
