### ISSUE TITLE
Cannot find Red Pitaya on LAN despite able to connect through browser

### ISSUE THREAD

**Issue by jagerber48** [lneuhaus/pyrpl#416] opened 2020-07-29 11:31 UTC
I am setting up pyrpl for the first time to connect with a Red Pitaya. I am able to connect to the Red Pitaya by connecting to hostname 192.168.1.129 in my web browser and access STEMlab functionality. However, when I try to start pyrpl (either through binary executable or  `python -m pyrpl` it does not find the Red Pitaya on the network. If I manually type in the IP address above I get 

```
Could not connect to Red Pitaya device with the following parameters:
...
Error message: [WinError 10054] An existing connection was forcibly closed by the remote host...
```

Occasionally when "Searching LAN for Red Pitayas" I get the error:

```
ERROR:paramiko.transport:Socket exception: An existing connection was forcibly closed by the remote host(10054)
```

**Comment by lneuhaus** [comment] 2020-11-17 13:00
Closing this because I cannot reproduce this. In case this proves to be a blocker please re-open and try to supply more information

**Closed by lneuhaus** 2020-11-17 13:00 UTC
